#token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNjg2MjU4NzE2LCJleHAiOjE2ODYyNjIzMTYyfQ.v4a-hG7o53u0f_1Z5uW533sJ1h4N5W7N0

### Authentication

#### Register
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

#### Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

#### Verify Token
POST http://localhost:3000/verify
Authorization: Bearer {{token}}

### Todos

#### Get All Todos
GET http://localhost:3000/api/todos
Authorization: Bearer {{token}}

#### Get Todo by Id
GET http://localhost:3000/api/todos/1234567890123
Authorization: Bearer {{token}}

#### Create New Todo
POST http://localhost:3000/api/todos
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Новая задача",
  "description": "Описание новой задачи"
}

#### Update Todo
PUT http://localhost:3000/api/todos/1234567890123
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Обновленная задача",
  "description": "Обновленное описание"
}

#### Delete Todo
DELETE http://localhost:3000/api/todos/1234567890123
Authorization: Bearer {{token}}